import { Branch, Product, Batch, InterBranchTransfer, Sale } from './types';

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'ACCRA_MAIN',
    name: 'Accra Central Main Depot',
    code: 'ACC-01',
    location: 'Derby Avenue, Okaishie Market District, Accra',
    phone: '+233 24 412 3456',
    manager: 'Kofi Mensah (Pharm. D)',
    isMainDepot: true,
  },
  {
    id: 'OSU_BRANCH',
    name: 'Osu Oxford Street Branch',
    code: 'OSU-02',
    location: 'Oxford Street, Near Danquah Circle, Osu',
    phone: '+233 20 899 7711',
    manager: 'Abena Osei (Pharm)',
  },
  {
    id: 'SPINTEX_BRANCH',
    name: 'Spintex Coastal Branch',
    code: 'SPN-03',
    location: 'Spintex Road, Opposite Coastal Junction, Accra',
    phone: '+233 30 255 4433',
    manager: 'Kwame Addo (Pharm)',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // --- ANTI-MALARIALS ---
  {
    id: 'PROD-LONART-DS',
    brandName: 'Lonart DS (Artemether 80/480mg)',
    genericName: 'Artemether + Lumefantrine Double Strength',
    category: 'Anti-Malarial',
    dosageForm: 'Tablets',
    strength: '80mg/480mg',
    packSize: 'Box of 6 Tablets',
    retailPrice: 45.00,
    costPrice: 32.00,
    reorderLevel: 45,
    requiresPrescription: true,
    nafdacOrFdaNo: 'FDA/SD.21-0419',
  },
  {
    id: 'PROD-COARTEM-20',
    brandName: 'Coartem 20/120mg',
    genericName: 'Artemether + Lumefantrine',
    category: 'Anti-Malarial',
    dosageForm: 'Tablets',
    strength: '20mg/120mg',
    packSize: 'Pack of 24 Tablets',
    retailPrice: 58.00,
    costPrice: 44.00,
    reorderLevel: 30,
    requiresPrescription: true,
    nafdacOrFdaNo: 'FDA/SD.19-8832',
  },
  {
    id: 'PROD-ARTEQUICK',
    brandName: 'Artequick Tablets',
    genericName: 'Artemisinin + Piperaquine',
    category: 'Anti-Malarial',
    dosageForm: 'Tablets',
    strength: '125mg/750mg',
    packSize: 'Pack of 4 Tablets',
    retailPrice: 52.00,
    costPrice: 37.50,
    reorderLevel: 25,
    requiresPrescription: true,
    nafdacOrFdaNo: 'FDA/SD.22-1102',
  },
  {
    id: 'PROD-MALAFANT-SYRUP',
    brandName: 'Malafant Pediatric Dry Syrup',
    genericName: 'Artemether + Lumefantrine Suspension',
    category: 'Anti-Malarial',
    dosageForm: 'Oral Suspension',
    strength: '180mg/1080mg per 60ml',
    packSize: 'Bottle 60ml',
    retailPrice: 38.00,
    costPrice: 26.00,
    reorderLevel: 20,
    requiresPrescription: true,
    nafdacOrFdaNo: 'FDA/SD.20-7451',
  },

  // --- ANTIBIOTICS ---
  {
    id: 'PROD-LETAP-AMOX-500',
    brandName: 'Letap Amoxicillin 500mg',
    genericName: 'Amoxicillin Trihydrate',
    category: 'Antibiotic',
    dosageForm: 'Capsules',
    strength: '500mg',
    packSize: 'Blister Pack 10s',
    retailPrice: 22.00,
    costPrice: 14.00,
    reorderLevel: 60,
    requiresPrescription: true,
    nafdacOrFdaNo: 'FDA/SD.18-3310',
  },
  {
    id: 'PROD-AUGMENTIN-625',
    brandName: 'Augmentin 625mg',
    genericName: 'Amoxicillin + Clavulanic Acid',
    category: 'Antibiotic',
    dosageForm: 'Tablets',
    strength: '500mg/125mg',
    packSize: 'Pack of 14 Tablets',
    retailPrice: 110.00,
    costPrice: 82.00,
    reorderLevel: 35,
    requiresPrescription: true,
    nafdacOrFdaNo: 'FDA/SD.23-0091',
  },
  {
    id: 'PROD-CIPRO-500',
    brandName: 'Kinapharma Ciprofloxacin 500mg',
    genericName: 'Ciprofloxacin Hydrochloride',
    category: 'Antibiotic',
    dosageForm: 'Tablets',
    strength: '500mg',
    packSize: 'Blister Pack 10s',
    retailPrice: 28.00,
    costPrice: 18.00,
    reorderLevel: 40,
    requiresPrescription: true,
    nafdacOrFdaNo: 'FDA/SD.19-4509',
  },
  {
    id: 'PROD-AZITHRO-500',
    brandName: 'Azithromycin 500mg (Zithro-3)',
    genericName: 'Azithromycin Dihydrate',
    category: 'Antibiotic',
    dosageForm: 'Tablets',
    strength: '500mg',
    packSize: 'Pack of 3 Tablets',
    retailPrice: 42.00,
    costPrice: 28.00,
    reorderLevel: 30,
    requiresPrescription: true,
    nafdacOrFdaNo: 'FDA/SD.21-9921',
  },

  // --- ANALGESICS & PAIN RELIEF ---
  {
    id: 'PROD-EMZOR-PARA',
    brandName: 'Emzor Paracetamol 500mg',
    genericName: 'Paracetamol / Acetaminophen',
    category: 'Analgesics & Pain',
    dosageForm: 'Tablets',
    strength: '500mg',
    packSize: 'Pack of 20 Tablets',
    retailPrice: 12.00,
    costPrice: 7.50,
    reorderLevel: 80,
    requiresPrescription: false,
    nafdacOrFdaNo: 'FDA/SD.17-1002',
  },
  {
    id: 'PROD-DICLO-GEL',
    brandName: 'Diclofenac Sodium Gel 1%',
    genericName: 'Diclofenac Topical Gel',
    category: 'Analgesics & Pain',
    dosageForm: 'Gel / Ointment',
    strength: '1% w/w',
    packSize: 'Tube 20g',
    retailPrice: 25.00,
    costPrice: 16.00,
    reorderLevel: 25,
    requiresPrescription: false,
    nafdacOrFdaNo: 'FDA/SD.20-5643',
  },
  {
    id: 'PROD-ERNEST-IBU-400',
    brandName: 'Ernest Ibuprofen 400mg',
    genericName: 'Ibuprofen',
    category: 'Analgesics & Pain',
    dosageForm: 'Tablets',
    strength: '400mg',
    packSize: 'Blister Pack 10s',
    retailPrice: 15.00,
    costPrice: 9.00,
    reorderLevel: 50,
    requiresPrescription: false,
    nafdacOrFdaNo: 'FDA/SD.18-8821',
  },

  // --- CARDIOVASCULAR & CHRONIC ---
  {
    id: 'PROD-AMLODIPINE-10',
    brandName: 'Amlodipine 10mg Tablets',
    genericName: 'Amlodipine Besylate',
    category: 'Cardiovascular & Chronic',
    dosageForm: 'Tablets',
    strength: '10mg',
    packSize: 'Pack of 30 Tablets',
    retailPrice: 35.00,
    costPrice: 21.00,
    reorderLevel: 35,
    requiresPrescription: true,
    nafdacOrFdaNo: 'FDA/SD.21-6677',
  },
  {
    id: 'PROD-LISINOPRIL-10',
    brandName: 'Lisinopril 10mg Tablets',
    genericName: 'Lisinopril Dihydrate',
    category: 'Cardiovascular & Chronic',
    dosageForm: 'Tablets',
    strength: '10mg',
    packSize: 'Pack of 28 Tablets',
    retailPrice: 40.00,
    costPrice: 25.00,
    reorderLevel: 30,
    requiresPrescription: true,
    nafdacOrFdaNo: 'FDA/SD.22-3341',
  },
  {
    id: 'PROD-METFORMIN-500',
    brandName: 'Metformin 500mg',
    genericName: 'Metformin Hydrochloride',
    category: 'Cardiovascular & Chronic',
    dosageForm: 'Tablets',
    strength: '500mg',
    packSize: 'Pack of 100 Tablets',
    retailPrice: 65.00,
    costPrice: 42.00,
    reorderLevel: 40,
    requiresPrescription: true,
    nafdacOrFdaNo: 'FDA/SD.20-1198',
  },

  // --- SYRUPS & REHYDRATION ---
  {
    id: 'PROD-BENYLIN-4FLU',
    brandName: 'Benylin 4Flu Cough Liquid',
    genericName: 'Diphenhydramine + Pseudoephedrine + Paracetamol',
    category: 'Syrups & Rehydration',
    dosageForm: 'Syrup',
    strength: '100ml Liquid',
    packSize: 'Bottle 100ml',
    retailPrice: 48.00,
    costPrice: 34.00,
    reorderLevel: 25,
    requiresPrescription: false,
    nafdacOrFdaNo: 'FDA/SD.19-2041',
  },
  {
    id: 'PROD-FEROGLOBIN',
    brandName: 'Feroglobin Liquid 200ml',
    genericName: 'Iron + Zinc + B-Complex Syrup',
    category: 'Syrups & Rehydration',
    dosageForm: 'Syrup',
    strength: '200ml Liquid',
    packSize: 'Bottle 200ml',
    retailPrice: 85.00,
    costPrice: 62.00,
    reorderLevel: 20,
    requiresPrescription: false,
    nafdacOrFdaNo: 'FDA/SD.21-0099',
  },
  {
    id: 'PROD-ORS-SACHETS',
    brandName: 'Royal ORS Sachets (Oral Rehydration)',
    genericName: 'Sodium Chloride + Glucose + Potassium',
    category: 'Syrups & Rehydration',
    dosageForm: 'Sachet / Powder',
    strength: '20.5g Sachet',
    packSize: 'Box of 10 Sachets',
    retailPrice: 20.00,
    costPrice: 12.00,
    reorderLevel: 100,
    requiresPrescription: false,
    nafdacOrFdaNo: 'FDA/SD.16-5541',
  },
  {
    id: 'PROD-ZENTEL-400',
    brandName: 'Zentel 400mg Chewable',
    genericName: 'Albendazole Dewormer',
    category: 'OTC & General Wellness',
    dosageForm: 'Tablets',
    strength: '400mg',
    packSize: 'Single Tablet Pack',
    retailPrice: 18.00,
    costPrice: 11.50,
    reorderLevel: 45,
    requiresPrescription: false,
    nafdacOrFdaNo: 'FDA/SD.20-8812',
  },
];

export const INITIAL_BATCHES: Batch[] = [
  // === ACCRA MAIN DEPOT BATCHES ===
  {
    id: 'BATCH-LONART-ACC-01',
    productId: 'PROD-LONART-DS',
    branchId: 'ACCRA_MAIN',
    batchNumber: 'LNT-2024-B102',
    quantity: 65,
    mfgDate: '2024-03-10',
    expiryDate: '2027-03-09',
    supplier: 'Bliss GVS Ghana Wholesale',
    locationShelf: 'Shelf A-02',
  },
  {
    id: 'BATCH-LONART-ACC-02 (EARLY)',
    productId: 'PROD-LONART-DS',
    branchId: 'ACCRA_MAIN',
    batchNumber: 'LNT-2023-A99',
    quantity: 18,
    mfgDate: '2023-11-01',
    expiryDate: '2026-10-15',
    supplier: 'Bliss GVS Ghana Wholesale',
    locationShelf: 'Shelf A-01 (Front)',
  },
  {
    id: 'BATCH-COART-ACC-01',
    productId: 'PROD-COARTEM-20',
    branchId: 'ACCRA_MAIN',
    batchNumber: 'CRT-9812-GH',
    quantity: 40,
    mfgDate: '2024-01-15',
    expiryDate: '2027-01-14',
    supplier: 'Novartis West Africa Depot',
    locationShelf: 'Shelf A-04',
  },
  {
    id: 'BATCH-AMOX-ACC-01',
    productId: 'PROD-LETAP-AMOX-500',
    branchId: 'ACCRA_MAIN',
    batchNumber: 'LTP-AMX-551',
    quantity: 110,
    mfgDate: '2024-05-01',
    expiryDate: '2027-05-01',
    supplier: 'Letap Pharmaceuticals Ltd (Accra)',
    locationShelf: 'Shelf B-01',
  },
  {
    id: 'BATCH-AUG-ACC-01',
    productId: 'PROD-AUGMENTIN-625',
    branchId: 'ACCRA_MAIN',
    batchNumber: 'GSK-AUG-2024',
    quantity: 24,
    mfgDate: '2024-02-10',
    expiryDate: '2026-11-30',
    supplier: 'GSK Ghana Wholesalers',
    locationShelf: 'Shelf B-03 (Rx)',
  },
  {
    id: 'BATCH-EMZ-ACC-01',
    productId: 'PROD-EMZOR-PARA',
    branchId: 'ACCRA_MAIN',
    batchNumber: 'EMZ-PCM-4401',
    quantity: 250,
    mfgDate: '2024-06-01',
    expiryDate: '2028-06-01',
    supplier: 'Okaishie Central Drug Lane',
    locationShelf: 'Dispensing Rack C-1',
  },
  {
    id: 'BATCH-AML-ACC-01',
    productId: 'PROD-AMLODIPINE-10',
    branchId: 'ACCRA_MAIN',
    batchNumber: 'AML-10-882',
    quantity: 50,
    mfgDate: '2024-04-12',
    expiryDate: '2027-04-12',
    supplier: 'Tobbinco Pharmaceuticals Depot',
    locationShelf: 'Chronic Rack D-02',
  },
  {
    id: 'BATCH-BEN-ACC-01',
    productId: 'PROD-BENYLIN-4FLU',
    branchId: 'ACCRA_MAIN',
    batchNumber: 'BNL-4F-2024',
    quantity: 12,
    mfgDate: '2024-01-20',
    expiryDate: '2026-09-30',
    supplier: 'Ernest Chemists Wholesale',
    locationShelf: 'Syrup Rack E-01',
  },
  {
    id: 'BATCH-ORS-ACC-01',
    productId: 'PROD-ORS-SACHETS',
    branchId: 'ACCRA_MAIN',
    batchNumber: 'ORS-RYL-009',
    quantity: 180,
    mfgDate: '2024-04-01',
    expiryDate: '2027-12-31',
    supplier: 'M&G Pharmaceuticals',
    locationShelf: 'OTC Section F-05',
  },

  // === OSU BRANCH BATCHES ===
  {
    id: 'BATCH-LONART-OSU-01',
    productId: 'PROD-LONART-DS',
    branchId: 'OSU_BRANCH',
    batchNumber: 'LNT-OSU-221',
    quantity: 12,
    mfgDate: '2024-02-14',
    expiryDate: '2027-02-14',
    supplier: 'Bliss GVS Ghana Wholesale',
    locationShelf: 'Counter Drawer 1',
  },
  {
    id: 'BATCH-AUG-OSU-01',
    productId: 'PROD-AUGMENTIN-625',
    branchId: 'OSU_BRANCH',
    batchNumber: 'GSK-AUG-2024-B',
    quantity: 5,
    mfgDate: '2024-03-01',
    expiryDate: '2027-03-01',
    supplier: 'GSK Ghana Wholesalers',
    locationShelf: 'Rx Cabinet 2',
  },
  {
    id: 'BATCH-CIP-OSU-01',
    productId: 'PROD-CIPRO-500',
    branchId: 'OSU_BRANCH',
    batchNumber: 'KNP-CPR-502',
    quantity: 35,
    mfgDate: '2024-01-10',
    expiryDate: '2026-08-10',
    supplier: 'Kinapharma Ltd',
    locationShelf: 'Quarantine Bay',
  },
  {
    id: 'BATCH-EMZ-OSU-01',
    productId: 'PROD-EMZOR-PARA',
    branchId: 'OSU_BRANCH',
    batchNumber: 'EMZ-PCM-4402',
    quantity: 85,
    mfgDate: '2024-06-01',
    expiryDate: '2028-06-01',
    supplier: 'Okaishie Central Drug Lane',
    locationShelf: 'Front Counter',
  },
  {
    id: 'BATCH-FER-OSU-01',
    productId: 'PROD-FEROGLOBIN',
    branchId: 'OSU_BRANCH',
    batchNumber: 'VTB-FER-110',
    quantity: 8,
    mfgDate: '2024-02-15',
    expiryDate: '2027-02-15',
    supplier: 'Ernest Chemists Wholesale',
    locationShelf: 'Cold Storage Racks',
  },

  // === SPINTEX BRANCH BATCHES ===
  {
    id: 'BATCH-LONART-SPN-01',
    productId: 'PROD-LONART-DS',
    branchId: 'SPINTEX_BRANCH',
    batchNumber: 'LNT-SPN-881',
    quantity: 6,
    mfgDate: '2024-03-10',
    expiryDate: '2027-03-09',
    supplier: 'Bliss GVS Ghana Wholesale',
    locationShelf: 'Main Counter A',
  },
  {
    id: 'BATCH-COART-SPN-01',
    productId: 'PROD-COARTEM-20',
    branchId: 'SPINTEX_BRANCH',
    batchNumber: 'CRT-SPN-330',
    quantity: 4,
    mfgDate: '2024-01-15',
    expiryDate: '2027-01-14',
    supplier: 'Novartis West Africa Depot',
    locationShelf: 'Main Counter B',
  },
  {
    id: 'BATCH-AMOX-SPN-01',
    productId: 'PROD-LETAP-AMOX-500',
    branchId: 'SPINTEX_BRANCH',
    batchNumber: 'LTP-AMX-599',
    quantity: 45,
    mfgDate: '2024-05-01',
    expiryDate: '2027-05-01',
    supplier: 'Letap Pharmaceuticals Ltd (Accra)',
    locationShelf: 'Shelf 3-B',
  },
  {
    id: 'BATCH-MET-SPN-01',
    productId: 'PROD-METFORMIN-500',
    branchId: 'SPINTEX_BRANCH',
    batchNumber: 'MET-500-112',
    quantity: 28,
    mfgDate: '2024-02-20',
    expiryDate: '2027-02-20',
    supplier: 'Tobbinco Pharmaceuticals Depot',
    locationShelf: 'Chronic Shelf D',
  },
  {
    id: 'BATCH-ZNT-SPN-01',
    productId: 'PROD-ZENTEL-400',
    branchId: 'SPINTEX_BRANCH',
    batchNumber: 'GSK-ZNT-09',
    quantity: 15,
    mfgDate: '2024-04-01',
    expiryDate: '2026-10-01',
    supplier: 'GSK Ghana Wholesalers',
    locationShelf: 'OTC Bin 12',
  },
];

export const INITIAL_TRANSFERS: InterBranchTransfer[] = [
  {
    id: 'TRF-2026-001',
    transferNo: 'TRF-GH-1092',
    sourceBranchId: 'ACCRA_MAIN',
    destinationBranchId: 'SPINTEX_BRANCH',
    items: [
      {
        productId: 'PROD-LONART-DS',
        productName: 'Lonart DS (Artemether 80/480mg)',
        batchId: 'BATCH-LONART-ACC-01',
        batchNumber: 'LNT-2024-B102',
        quantity: 15,
        expiryDate: '2027-03-09',
      },
    ],
    status: 'RECEIVED',
    notes: 'Urgent stock top-up for Spintex high demand',
    requestedBy: 'Kwame Addo (Spintex)',
    createdAt: '2026-08-25T09:30:00Z',
    dispatchedAt: '2026-08-25T11:00:00Z',
    receivedAt: '2026-08-25T14:15:00Z',
  },
  {
    id: 'TRF-2026-002',
    transferNo: 'TRF-GH-1093',
    sourceBranchId: 'ACCRA_MAIN',
    destinationBranchId: 'OSU_BRANCH',
    items: [
      {
        productId: 'PROD-AUGMENTIN-625',
        productName: 'Augmentin 625mg',
        batchId: 'BATCH-AUG-ACC-01',
        batchNumber: 'GSK-AUG-2024',
        quantity: 10,
        expiryDate: '2026-11-30',
      },
    ],
    status: 'DISPATCHED',
    notes: 'Dispatched via dispatch rider to Osu Branch',
    requestedBy: 'Abena Osei (Osu)',
    createdAt: '2026-08-26T16:00:00Z',
    dispatchedAt: '2026-08-26T17:30:00Z',
  },
];

export const INITIAL_SALES: Sale[] = [
  {
    id: 'SALE-2026-001',
    receiptNumber: 'INV-GH-8801',
    branchId: 'ACCRA_MAIN',
    timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    items: [
      {
        product: INITIAL_PRODUCTS[0],
        selectedBatch: INITIAL_BATCHES[0],
        quantity: 2,
        unitPrice: 45.00,
        discount: 0,
        lineTotal: 90.00,
      },
      {
        product: INITIAL_PRODUCTS[8],
        selectedBatch: INITIAL_BATCHES[5],
        quantity: 1,
        unitPrice: 12.00,
        discount: 0,
        lineTotal: 12.00,
      },
    ],
    subtotal: 102.00,
    discount: 0,
    tax: 0,
    total: 102.00,
    payment: {
      method: 'CASH',
      cashPaid: 110.00,
      cashChange: 8.00,
      customerName: 'Kojo Antwi',
      customerPhone: '0244123890',
    },
    attendantName: 'Kofi Mensah (Pharm)',
    synced: true,
  },
  {
    id: 'SALE-2026-002',
    receiptNumber: 'INV-GH-8802',
    branchId: 'OSU_BRANCH',
    timestamp: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    items: [
      {
        product: INITIAL_PRODUCTS[5],
        selectedBatch: INITIAL_BATCHES[9],
        quantity: 1,
        unitPrice: 110.00,
        discount: 5.00,
        lineTotal: 105.00,
      },
    ],
    subtotal: 110.00,
    discount: 5.00,
    tax: 0,
    total: 105.00,
    payment: {
      method: 'MOMO_MTN',
      momoAmount: 105.00,
      momoProvider: 'MTN Mobile Money',
      momoRef: 'MTN-883920194',
      customerName: 'Ama Serwaa',
      customerPhone: '0249876543',
    },
    attendantName: 'Abena Osei (Pharm)',
    synced: true,
  },
  {
    id: 'SALE-2026-003',
    receiptNumber: 'INV-GH-8803',
    branchId: 'ACCRA_MAIN',
    timestamp: new Date(Date.now() - 1 * 86400 * 1000).toISOString(),
    items: [
      {
        product: INITIAL_PRODUCTS[1],
        selectedBatch: INITIAL_BATCHES[2],
        quantity: 1,
        unitPrice: 58.00,
        discount: 0,
        lineTotal: 58.00,
      },
      {
        product: INITIAL_PRODUCTS[16],
        selectedBatch: INITIAL_BATCHES[8],
        quantity: 2,
        unitPrice: 20.00,
        discount: 0,
        lineTotal: 40.00,
      },
    ],
    subtotal: 98.00,
    discount: 0,
    tax: 0,
    total: 98.00,
    payment: {
      method: 'SPLIT',
      cashPaid: 50.00,
      cashChange: 0,
      momoAmount: 48.00,
      momoProvider: 'Telecel Cash',
      momoRef: 'TEL-4439102',
      customerName: 'Ebenezer Lartey',
      customerPhone: '0201122334',
    },
    attendantName: 'Kofi Mensah (Pharm)',
    synced: true,
  },
];
